# 支付服务端口号
server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.31.200
      port: 8500
      discovery:
        service-name: ${spring.application.name}


